-- Migracion aditiva y transaccional.
-- No elimina ni reemplaza objetos existentes. Si encuentra un conflicto, aborta
-- antes de crear nada y PostgreSQL revierte toda la transaccion.
begin;

do $$
declare
    missing_columns text[];
begin
    if to_regclass('public.usuarios') is null then
        raise exception 'Migracion cancelada: no existe public.usuarios.';
    end if;

    if to_regclass('public.banners') is not null
       or to_regclass('public.notificaciones') is not null then
        raise exception 'Migracion cancelada: banners o notificaciones ya existe. No se modifico ninguna tabla.';
    end if;

    if to_regprocedure('public.fhec_registrar_notificaciones_banner_20260722()') is not null then
        raise exception 'Migracion cancelada: la funcion de notificaciones ya existe.';
    end if;

    select array_agg(required.column_name)
    into missing_columns
    from unnest(array[
        'id',
        'rol',
        'telefono',
        'codigo_area',
        'acepta_promociones',
        'acepta_promociones_sms',
        'acepta_promociones_correo',
        'acepta_notificaciones',
        'acepta_notificaciones_sms',
        'acepta_notificaciones_correo'
    ]) as required(column_name)
    where not exists (
        select 1
        from information_schema.columns c
        where c.table_schema = 'public'
          and c.table_name = 'usuarios'
          and c.column_name = required.column_name
    );

    if missing_columns is not null then
        raise exception 'Migracion cancelada: faltan columnas en usuarios: %', array_to_string(missing_columns, ', ');
    end if;
end;
$$;

create table public.banners (
    id_banner bigint generated by default as identity primary key,
    titulo text not null check (char_length(trim(titulo)) between 1 and 120),
    subtitulo text,
    etiqueta text,
    texto_accion text,
    url_accion text,
    url_imagen text not null,
    color_inicio text not null default '#031b24',
    color_medio text not null default '#00546a',
    color_fin text not null default '#50e9f8',
    fecha_creacion timestamptz not null default now()
);

create table public.notificaciones (
    id_notificacion bigint generated by default as identity primary key,
    id_usuario uuid not null references public.usuarios(id) on delete cascade,
    id_banner bigint references public.banners(id_banner) on delete set null,
    titulo text not null,
    mensaje text not null,
    fecha_notificacion timestamptz not null default now(),
    leida boolean not null default false,
    tipo_notificacion text not null default 'promocional',
    canales_solicitados text[] not null default array['in_app']::text[],
    canales_enviados text[] not null default array['in_app']::text[],
    estado_envio jsonb not null default '{"in_app":"enviado"}'::jsonb,
    correo_destino text,
    telefono_destino text,
    constraint notificaciones_usuario_banner_unique unique (id_usuario, id_banner)
);

create index notificaciones_usuario_fecha_idx
    on public.notificaciones (id_usuario, fecha_notificacion desc);
create index notificaciones_banner_idx
    on public.notificaciones (id_banner) where id_banner is not null;

-- Datos iniciales: se insertan antes de crear el trigger, por lo que no generan
-- notificaciones promocionales ni alteran ninguna tabla preexistente.
insert into public.banners (titulo, subtitulo, etiqueta, texto_accion, url_imagen)
values
    ('Control de Diabetes', 'Medicamentos de primera línea con los mejores precios del mercado venezolano.', 'HASTA 20% OFF', 'Ver Medicamentos →', 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=900&h=500&fit=crop&auto=format'),
    ('Vitaminas & Suplementos', 'Refuerza tu sistema inmune con los mejores suplementos. Entrega rápida en Ciudad Guayana.', 'DESTACADOS', 'Explorar Vitaminas →', 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=900&h=500&fit=crop&auto=format'),
    ('Salud Cardiovascular', 'Tratamientos completos para cuidar tu corazón. Pedido con o sin récipe médico.', 'RECOMENDADO', 'Ver Cardioprotectores →', 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=900&h=500&fit=crop&auto=format');

alter table public.banners enable row level security;
alter table public.notificaciones enable row level security;

create policy "banners_public_read"
    on public.banners for select
    using (true);

create policy "banners_superadmin_insert"
    on public.banners for insert to authenticated
    with check (exists (
        select 1 from public.usuarios u
        where u.id = auth.uid() and u.rol in ('super_admin', 'superadmin')
    ));

create policy "banners_superadmin_update"
    on public.banners for update to authenticated
    using (exists (
        select 1 from public.usuarios u
        where u.id = auth.uid() and u.rol in ('super_admin', 'superadmin')
    ))
    with check (exists (
        select 1 from public.usuarios u
        where u.id = auth.uid() and u.rol in ('super_admin', 'superadmin')
    ));

create policy "banners_superadmin_delete"
    on public.banners for delete to authenticated
    using (exists (
        select 1 from public.usuarios u
        where u.id = auth.uid() and u.rol in ('super_admin', 'superadmin')
    ));

create policy "notificaciones_own_read"
    on public.notificaciones for select to authenticated
    using (id_usuario = auth.uid());

create policy "notificaciones_own_update"
    on public.notificaciones for update to authenticated
    using (id_usuario = auth.uid())
    with check (id_usuario = auth.uid());

create policy "notificaciones_own_delete"
    on public.notificaciones for delete to authenticated
    using (id_usuario = auth.uid());

create function public.fhec_registrar_notificaciones_banner_20260722()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
begin
    insert into public.notificaciones (
        id_usuario,
        id_banner,
        titulo,
        mensaje,
        tipo_notificacion,
        canales_solicitados,
        correo_destino,
        telefono_destino
    )
    select
        u.id,
        new.id_banner,
        new.titulo,
        coalesce(nullif(trim(new.subtitulo), ''), new.titulo),
        'promocional',
        array_remove(array[
            'in_app',
            case
                when coalesce(u.acepta_promociones_correo, false)
                 and coalesce(u.acepta_notificaciones_correo, false)
                 and au.email is not null then 'correo'
            end,
            case
                when coalesce(u.acepta_promociones_sms, false)
                 and coalesce(u.acepta_notificaciones_sms, false)
                 and u.telefono is not null then 'sms'
            end
        ], null),
        case
            when coalesce(u.acepta_promociones_correo, false)
             and coalesce(u.acepta_notificaciones_correo, false) then au.email
        end,
        case
            when coalesce(u.acepta_promociones_sms, false)
             and coalesce(u.acepta_notificaciones_sms, false) then concat(coalesce(u.codigo_area, ''), u.telefono)
        end
    from public.usuarios u
    left join auth.users au on au.id = u.id
    where coalesce(u.acepta_promociones, false)
      and coalesce(u.acepta_notificaciones, false);

    return new;
end;
$$;

create trigger banners_registrar_notificaciones_20260722
after insert on public.banners
for each row execute function public.fhec_registrar_notificaciones_banner_20260722();

commit;
